
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.30/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The system is: Windows - 10.0.19045 - AMD64
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.30/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files/CMake/share/cmake-3.30/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files/CMake/share/cmake-3.30/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler:  
      Build flags: /DWIN32;/D_WINDOWS
      Id flags:  
      
      The output was:
      0
      Microsoft (R) Build Engine ўҐабЁЁ 17.2.1+52cd2da31 ¤«п .NET Framework
      (C) Љ®аЇ®а жЁп Њ ©Єа®б®дв (Microsoft Corporation). ‚бҐ Їа ў  § йЁйҐ­л.
      
      ‘Ў®аЄ  ­ з в  04.07.2024 0:29:51.
      Џа®ҐЄв "D:\\Users\\Jacarax\\Desktop\\ђ Ў®в \\1\\1\\cmake\\CMakeFiles\\3.30.0\\CompilerIdC\\CompilerIdC.vcxproj" ў г§«Ґ 1 (жҐ«ҐўлҐ ®ЎкҐЄвл Ї® г¬®«з ­Ёо).
      PrepareForBuild:
        ‘®§¤ ­ЁҐ Є в «®Ј  "Debug\\".
        ‘®§¤ ­ЁҐ Є в «®Ј  "Debug\\CompilerIdC.tlog\\".
      InitializeBuildStatus:
        ‘®§¤ ­ЁҐ "Debug\\CompilerIdC.tlog\\unsuccessfulbuild", в Є Є Є Ўл«® § ¤ ­® "AlwaysCreate".
      ClCompile:
        D:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.32.31326\\bin\\HostX64\\x64\\CL.exe /c /nologo /W0 /WX- /diagnostics:column /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc143.pdb" /external:W0 /Gd /TC /FC /errorReport:queue CMakeCCompilerId.c
        CMakeCCompilerId.c
      Link:
        D:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.32.31326\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:".\\CompilerIdC.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\\CompilerIdC.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\\CompilerIdC.lib" /MACHINE:X64 Debug\\CMakeCCompilerId.obj
        CompilerIdC.vcxproj -> D:\\Users\\Jacarax\\Desktop\\ђ Ў®в \\1\\1\\cmake\\CMakeFiles\\3.30.0\\CompilerIdC\\CompilerIdC.exe
      PostBuildEvent:
        for %%i in (cl.exe) do @echo CMAKE_C_COMPILER=%%~$PATH:i
        :VCEnd
        CMAKE_C_COMPILER=D:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.32.31326\\bin\\Hostx64\\x64\\cl.exe
      FinalizeBuildStatus:
        ” ©« "Debug\\CompilerIdC.tlog\\unsuccessfulbuild" г¤ «пҐвбп.
        ЋЎа йҐ­ЁҐ Є "Debug\\CompilerIdC.tlog\\CompilerIdC.lastbuildstate".
      ‘Ў®аЄ  Їа®ҐЄв  "D:\\Users\\Jacarax\\Desktop\\ђ Ў®в \\1\\1\\cmake\\CMakeFiles\\3.30.0\\CompilerIdC\\CompilerIdC.vcxproj" § ўҐаиҐ­  (жҐ«ҐўлҐ ®ЎкҐЄвл Ї® г¬®«з ­Ёо).
      
      ‘Ў®аЄ  гбЇҐи­® § ўҐаиҐ­ .
          ЏаҐ¤гЇаҐ¦¤Ґ­Ё©: 0
          ЋиЁЎ®Є: 0
      
      Џа®и«® ўаҐ¬Ґ­Ё 00:00:00.69
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.exe"
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.vcxproj"
      
      The C compiler identification is MSVC, found in:
        D:/Users/Jacarax/Desktop/Работа/1/1/cmake/CMakeFiles/3.30.0/CompilerIdC/CompilerIdC.exe
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.30/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files/CMake/share/cmake-3.30/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files/CMake/share/cmake-3.30/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler:  
      Build flags: /DWIN32;/D_WINDOWS;/EHsc
      Id flags:  
      
      The output was:
      0
      Microsoft (R) Build Engine ўҐабЁЁ 17.2.1+52cd2da31 ¤«п .NET Framework
      (C) Љ®аЇ®а жЁп Њ ©Єа®б®дв (Microsoft Corporation). ‚бҐ Їа ў  § йЁйҐ­л.
      
      ‘Ў®аЄ  ­ з в  04.07.2024 0:29:51.
      Џа®ҐЄв "D:\\Users\\Jacarax\\Desktop\\ђ Ў®в \\1\\1\\cmake\\CMakeFiles\\3.30.0\\CompilerIdCXX\\CompilerIdCXX.vcxproj" ў г§«Ґ 1 (жҐ«ҐўлҐ ®ЎкҐЄвл Ї® г¬®«з ­Ёо).
      PrepareForBuild:
        ‘®§¤ ­ЁҐ Є в «®Ј  "Debug\\".
        ‘®§¤ ­ЁҐ Є в «®Ј  "Debug\\CompilerIdCXX.tlog\\".
      InitializeBuildStatus:
        ‘®§¤ ­ЁҐ "Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild", в Є Є Є Ўл«® § ¤ ­® "AlwaysCreate".
      ClCompile:
        D:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.32.31326\\bin\\HostX64\\x64\\CL.exe /c /nologo /W0 /WX- /diagnostics:column /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc143.pdb" /external:W0 /Gd /TP /FC /errorReport:queue CMakeCXXCompilerId.cpp
        CMakeCXXCompilerId.cpp
      Link:
        D:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.32.31326\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:".\\CompilerIdCXX.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\\CompilerIdCXX.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\\CompilerIdCXX.lib" /MACHINE:X64 Debug\\CMakeCXXCompilerId.obj
        CompilerIdCXX.vcxproj -> D:\\Users\\Jacarax\\Desktop\\ђ Ў®в \\1\\1\\cmake\\CMakeFiles\\3.30.0\\CompilerIdCXX\\CompilerIdCXX.exe
      PostBuildEvent:
        for %%i in (cl.exe) do @echo CMAKE_CXX_COMPILER=%%~$PATH:i
        :VCEnd
        CMAKE_CXX_COMPILER=D:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.32.31326\\bin\\Hostx64\\x64\\cl.exe
      FinalizeBuildStatus:
        ” ©« "Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild" г¤ «пҐвбп.
        ЋЎа йҐ­ЁҐ Є "Debug\\CompilerIdCXX.tlog\\CompilerIdCXX.lastbuildstate".
      ‘Ў®аЄ  Їа®ҐЄв  "D:\\Users\\Jacarax\\Desktop\\ђ Ў®в \\1\\1\\cmake\\CMakeFiles\\3.30.0\\CompilerIdCXX\\CompilerIdCXX.vcxproj" § ўҐаиҐ­  (жҐ«ҐўлҐ ®ЎкҐЄвл Ї® г¬®«з ­Ёо).
      
      ‘Ў®аЄ  гбЇҐи­® § ўҐаиҐ­ .
          ЏаҐ¤гЇаҐ¦¤Ґ­Ё©: 0
          ЋиЁЎ®Є: 0
      
      Џа®и«® ўаҐ¬Ґ­Ё 00:00:00.53
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.exe"
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.vcxproj"
      
      The CXX compiler identification is MSVC, found in:
        D:/Users/Jacarax/Desktop/Работа/1/1/cmake/CMakeFiles/3.30.0/CompilerIdCXX/CompilerIdCXX.exe
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.30/Modules/CMakeDetermineCompilerABI.cmake:74 (try_compile)"
      - "C:/Program Files/CMake/share/cmake-3.30/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:2 (project)"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "D:/Users/Jacarax/Desktop/\u0420\u0430\u0431\u043e\u0442\u0430/1/1/cmake/CMakeFiles/CMakeScratch/TryCompile-n8o84t"
      binary: "D:/Users/Jacarax/Desktop/\u0420\u0430\u0431\u043e\u0442\u0430/1/1/cmake/CMakeFiles/CMakeScratch/TryCompile-n8o84t"
    cmakeVariables:
      CMAKE_C_FLAGS: "/DWIN32 /D_WINDOWS"
      CMAKE_C_FLAGS_DEBUG: "/Zi /Ob0 /Od /RTC1"
      CMAKE_EXE_LINKER_FLAGS: "/machine:x64"
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'D:/Users/Jacarax/Desktop/Работа/1/1/cmake/CMakeFiles/CMakeScratch/TryCompile-n8o84t'
        
        Run Build Command(s): "D:/Program Files/Microsoft Visual Studio/2022/Community/MSBuild/Current/Bin/amd64/MSBuild.exe" cmTC_71c58.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=17.0 /v:n
        Microsoft (R) Build Engine ўҐабЁЁ 17.2.1+52cd2da31 ¤«п .NET Framework
        (C) Љ®аЇ®а жЁп Њ ©Єа®б®дв (Microsoft Corporation). ‚бҐ Їа ў  § йЁйҐ­л.
        
        ‘Ў®аЄ  ­ з в  04.07.2024 0:29:52.
        Џа®ҐЄв "D:\\Users\\Jacarax\\Desktop\\ђ Ў®в \\1\\1\\cmake\\CMakeFiles\\CMakeScratch\\TryCompile-n8o84t\\cmTC_71c58.vcxproj" ў г§«Ґ 1 (жҐ«ҐўлҐ ®ЎкҐЄвл Ї® г¬®«з ­Ёо).
        PrepareForBuild:
          ‘®§¤ ­ЁҐ Є в «®Ј  "cmTC_71c58.dir\\Debug\\".
          ‘®§¤ ­ЁҐ Є в «®Ј  "D:\\Users\\Jacarax\\Desktop\\ђ Ў®в \\1\\1\\cmake\\CMakeFiles\\CMakeScratch\\TryCompile-n8o84t\\Debug\\".
          ‘®§¤ ­ЁҐ Є в «®Ј  "cmTC_71c58.dir\\Debug\\cmTC_71c58.tlog\\".
        InitializeBuildStatus:
          ‘®§¤ ­ЁҐ "cmTC_71c58.dir\\Debug\\cmTC_71c58.tlog\\unsuccessfulbuild", в Є Є Є Ўл«® § ¤ ­® "AlwaysCreate".
        ClCompile:
          D:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.32.31326\\bin\\HostX64\\x64\\CL.exe /c /Zi /W1 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_71c58.dir\\Debug\\\\" /Fd"cmTC_71c58.dir\\Debug\\vc143.pdb" /external:W1 /Gd /TC /errorReport:queue "C:\\Program Files\\CMake\\share\\cmake-3.30\\Modules\\CMakeCCompilerABI.c"
          ЋЇвЁ¬Ё§ЁагойЁ© Є®¬ЇЁ«пв®а Microsoft (R) C/C++ ўҐабЁЁ 19.32.31332 ¤«п x64
          CMakeCCompilerABI.c
          (C) Љ®аЇ®а жЁп Њ ©Єа®б®дв (Microsoft Corporation).  ‚бҐ Їа ў  § йЁйҐ­л.
          cl /c /Zi /W1 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_71c58.dir\\Debug\\\\" /Fd"cmTC_71c58.dir\\Debug\\vc143.pdb" /external:W1 /Gd /TC /errorReport:queue "C:\\Program Files\\CMake\\share\\cmake-3.30\\Modules\\CMakeCCompilerABI.c"
        Link:
          D:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.32.31326\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:"D:\\Users\\Jacarax\\Desktop\\ђ Ў®в \\1\\1\\cmake\\CMakeFiles\\CMakeScratch\\TryCompile-n8o84t\\Debug\\cmTC_71c58.exe" /INCREMENTAL /ILK:"cmTC_71c58.dir\\Debug\\cmTC_71c58.ilk" /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"D:/Users/Jacarax/Desktop/ђ Ў®в /1/1/cmake/CMakeFiles/CMakeScratch/TryCompile-n8o84t/Debug/cmTC_71c58.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"D:/Users/Jacarax/Desktop/ђ Ў®в /1/1/cmake/CMakeFiles/CMakeScratch/TryCompile-n8o84t/Debug/cmTC_71c58.lib" /MACHINE:X64  /machine:x64 cmTC_71c58.dir\\Debug\\CMakeCCompilerABI.obj
          cmTC_71c58.vcxproj -> D:\\Users\\Jacarax\\Desktop\\ђ Ў®в \\1\\1\\cmake\\CMakeFiles\\CMakeScratch\\TryCompile-n8o84t\\Debug\\cmTC_71c58.exe
        FinalizeBuildStatus:
          ” ©« "cmTC_71c58.dir\\Debug\\cmTC_71c58.tlog\\unsuccessfulbuild" г¤ «пҐвбп.
          ЋЎа йҐ­ЁҐ Є "cmTC_71c58.dir\\Debug\\cmTC_71c58.tlog\\cmTC_71c58.lastbuildstate".
        ‘Ў®аЄ  Їа®ҐЄв  "D:\\Users\\Jacarax\\Desktop\\ђ Ў®в \\1\\1\\cmake\\CMakeFiles\\CMakeScratch\\TryCompile-n8o84t\\cmTC_71c58.vcxproj" § ўҐаиҐ­  (жҐ«ҐўлҐ ®ЎкҐЄвл Ї® г¬®«з ­Ёо).
        
        ‘Ў®аЄ  гбЇҐи­® § ўҐаиҐ­ .
            ЏаҐ¤гЇаҐ¦¤Ґ­Ё©: 0
            ЋиЁЎ®Є: 0
        
        Џа®и«® ўаҐ¬Ґ­Ё 00:00:00.58
        
      exitCode: 0
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.30/Modules/CMakeDetermineCompilerABI.cmake:218 (message)"
      - "C:/Program Files/CMake/share/cmake-3.30/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Parsed C implicit link information:
        link line regex: [^( *|.*[/\\])(ld[0-9]*(\\.[a-z]+)?|link\\.exe|lld-link(\\.exe)?|CMAKE_LINK_STARTFILE-NOTFOUND|([^/\\]+-)?ld|collect2)[^/\\]*( |$)]
        linker tool regex: [^[ 	]*(->|")?[ 	]*(([^"]*[/\\])?(ld[0-9]*(\\.[a-z]+)?|link\\.exe|lld-link(\\.exe)?))("|,| |$)]
        linker tool for 'C': D:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.32.31326/bin/HostX64/x64/link.exe
        implicit libs: []
        implicit objs: []
        implicit dirs: []
        implicit fwks: []
      
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.30/Modules/Internal/CMakeDetermineLinkerId.cmake:40 (message)"
      - "C:/Program Files/CMake/share/cmake-3.30/Modules/CMakeDetermineCompilerABI.cmake:255 (cmake_determine_linker_id)"
      - "C:/Program Files/CMake/share/cmake-3.30/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Running the C compiler's linker: "D:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.32.31326/bin/HostX64/x64/link.exe" "-v"
      Microsoft (R) Incremental Linker Version 14.32.31332.0
      Copyright (C) Microsoft Corporation.  All rights reserved.
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.30/Modules/CMakeDetermineCompilerABI.cmake:74 (try_compile)"
      - "C:/Program Files/CMake/share/cmake-3.30/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:2 (project)"
    checks:
      - "Detecting CXX compiler ABI info"
    directories:
      source: "D:/Users/Jacarax/Desktop/\u0420\u0430\u0431\u043e\u0442\u0430/1/1/cmake/CMakeFiles/CMakeScratch/TryCompile-jft312"
      binary: "D:/Users/Jacarax/Desktop/\u0420\u0430\u0431\u043e\u0442\u0430/1/1/cmake/CMakeFiles/CMakeScratch/TryCompile-jft312"
    cmakeVariables:
      CMAKE_CXX_FLAGS: "/DWIN32 /D_WINDOWS /EHsc"
      CMAKE_CXX_FLAGS_DEBUG: "/Zi /Ob0 /Od /RTC1"
      CMAKE_CXX_SCAN_FOR_MODULES: "OFF"
      CMAKE_EXE_LINKER_FLAGS: "/machine:x64"
    buildResult:
      variable: "CMAKE_CXX_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'D:/Users/Jacarax/Desktop/Работа/1/1/cmake/CMakeFiles/CMakeScratch/TryCompile-jft312'
        
        Run Build Command(s): "D:/Program Files/Microsoft Visual Studio/2022/Community/MSBuild/Current/Bin/amd64/MSBuild.exe" cmTC_8d198.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=17.0 /v:n
        Microsoft (R) Build Engine ўҐабЁЁ 17.2.1+52cd2da31 ¤«п .NET Framework
        (C) Љ®аЇ®а жЁп Њ ©Єа®б®дв (Microsoft Corporation). ‚бҐ Їа ў  § йЁйҐ­л.
        
        ‘Ў®аЄ  ­ з в  04.07.2024 0:29:53.
        Џа®ҐЄв "D:\\Users\\Jacarax\\Desktop\\ђ Ў®в \\1\\1\\cmake\\CMakeFiles\\CMakeScratch\\TryCompile-jft312\\cmTC_8d198.vcxproj" ў г§«Ґ 1 (жҐ«ҐўлҐ ®ЎкҐЄвл Ї® г¬®«з ­Ёо).
        PrepareForBuild:
          ‘®§¤ ­ЁҐ Є в «®Ј  "cmTC_8d198.dir\\Debug\\".
          ‘®§¤ ­ЁҐ Є в «®Ј  "D:\\Users\\Jacarax\\Desktop\\ђ Ў®в \\1\\1\\cmake\\CMakeFiles\\CMakeScratch\\TryCompile-jft312\\Debug\\".
          ‘®§¤ ­ЁҐ Є в «®Ј  "cmTC_8d198.dir\\Debug\\cmTC_8d198.tlog\\".
        InitializeBuildStatus:
          ‘®§¤ ­ЁҐ "cmTC_8d198.dir\\Debug\\cmTC_8d198.tlog\\unsuccessfulbuild", в Є Є Є Ўл«® § ¤ ­® "AlwaysCreate".
        ClCompile:
          D:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.32.31326\\bin\\HostX64\\x64\\CL.exe /c /Zi /W1 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_8d198.dir\\Debug\\\\" /Fd"cmTC_8d198.dir\\Debug\\vc143.pdb" /external:W1 /Gd /TP /errorReport:queue "C:\\Program Files\\CMake\\share\\cmake-3.30\\Modules\\CMakeCXXCompilerABI.cpp"
          ЋЇвЁ¬Ё§ЁагойЁ© Є®¬ЇЁ«пв®а Microsoft (R) C/C++ ўҐабЁЁ 19.32.31332 ¤«п x64
          CMakeCXXCompilerABI.cpp
          (C) Љ®аЇ®а жЁп Њ ©Єа®б®дв (Microsoft Corporation).  ‚бҐ Їа ў  § йЁйҐ­л.
          cl /c /Zi /W1 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_8d198.dir\\Debug\\\\" /Fd"cmTC_8d198.dir\\Debug\\vc143.pdb" /external:W1 /Gd /TP /errorReport:queue "C:\\Program Files\\CMake\\share\\cmake-3.30\\Modules\\CMakeCXXCompilerABI.cpp"
        Link:
          D:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.32.31326\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:"D:\\Users\\Jacarax\\Desktop\\ђ Ў®в \\1\\1\\cmake\\CMakeFiles\\CMakeScratch\\TryCompile-jft312\\Debug\\cmTC_8d198.exe" /INCREMENTAL /ILK:"cmTC_8d198.dir\\Debug\\cmTC_8d198.ilk" /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"D:/Users/Jacarax/Desktop/ђ Ў®в /1/1/cmake/CMakeFiles/CMakeScratch/TryCompile-jft312/Debug/cmTC_8d198.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"D:/Users/Jacarax/Desktop/ђ Ў®в /1/1/cmake/CMakeFiles/CMakeScratch/TryCompile-jft312/Debug/cmTC_8d198.lib" /MACHINE:X64  /machine:x64 cmTC_8d198.dir\\Debug\\CMakeCXXCompilerABI.obj
          cmTC_8d198.vcxproj -> D:\\Users\\Jacarax\\Desktop\\ђ Ў®в \\1\\1\\cmake\\CMakeFiles\\CMakeScratch\\TryCompile-jft312\\Debug\\cmTC_8d198.exe
        FinalizeBuildStatus:
          ” ©« "cmTC_8d198.dir\\Debug\\cmTC_8d198.tlog\\unsuccessfulbuild" г¤ «пҐвбп.
          ЋЎа йҐ­ЁҐ Є "cmTC_8d198.dir\\Debug\\cmTC_8d198.tlog\\cmTC_8d198.lastbuildstate".
        ‘Ў®аЄ  Їа®ҐЄв  "D:\\Users\\Jacarax\\Desktop\\ђ Ў®в \\1\\1\\cmake\\CMakeFiles\\CMakeScratch\\TryCompile-jft312\\cmTC_8d198.vcxproj" § ўҐаиҐ­  (жҐ«ҐўлҐ ®ЎкҐЄвл Ї® г¬®«з ­Ёо).
        
        ‘Ў®аЄ  гбЇҐи­® § ўҐаиҐ­ .
            ЏаҐ¤гЇаҐ¦¤Ґ­Ё©: 0
            ЋиЁЎ®Є: 0
        
        Џа®и«® ўаҐ¬Ґ­Ё 00:00:00.57
        
      exitCode: 0
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.30/Modules/CMakeDetermineCompilerABI.cmake:218 (message)"
      - "C:/Program Files/CMake/share/cmake-3.30/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Parsed CXX implicit link information:
        link line regex: [^( *|.*[/\\])(ld[0-9]*(\\.[a-z]+)?|link\\.exe|lld-link(\\.exe)?|CMAKE_LINK_STARTFILE-NOTFOUND|([^/\\]+-)?ld|collect2)[^/\\]*( |$)]
        linker tool regex: [^[ 	]*(->|")?[ 	]*(([^"]*[/\\])?(ld[0-9]*(\\.[a-z]+)?|link\\.exe|lld-link(\\.exe)?))("|,| |$)]
        linker tool for 'CXX': D:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.32.31326/bin/HostX64/x64/link.exe
        implicit libs: []
        implicit objs: []
        implicit dirs: []
        implicit fwks: []
      
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.30/Modules/Internal/CMakeDetermineLinkerId.cmake:40 (message)"
      - "C:/Program Files/CMake/share/cmake-3.30/Modules/CMakeDetermineCompilerABI.cmake:255 (cmake_determine_linker_id)"
      - "C:/Program Files/CMake/share/cmake-3.30/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Running the CXX compiler's linker: "D:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.32.31326/bin/HostX64/x64/link.exe" "-v"
      Microsoft (R) Incremental Linker Version 14.32.31332.0
      Copyright (C) Microsoft Corporation.  All rights reserved.
...
